### ISSUE TITLE
Assistance Required for Matching Generated Feature Files with Configuration Settings

### ISSUE THREAD

**Issue by goon-13** [luigiluz/automotive-ids-evaluation-framework#2]
Hello, I generated the following files after running '_**executioner_feature_ generator. py**_':

_1.     _X_test_TOW_IDS_dataset_one_class_Wsize_44_Cols_116_Wslide_1_MC_False_sumX_True.npz
2.     X_train_TOW_IDS_dataset_multi_class_Wsize_44_Cols_116_Wslide_1_MC_True_sumX_True.npz
3.     y_test_TOW_IDS_dataset_one_class_Wsize_44_Cols_116_Wslide_1_MC_False_sumX_True.csv
4.     y_train_TOW_IDS_dataset_multi_class_Wsize_44_Cols_116_Wslide_1_MC_True_sumX_True.csv__

However, the file names specified for the input data in the configuration files within the directories '**_config_jsons/model_test_**' and '_**config_jsons/model_train_validate**_' do not match the files I have generated in the first step of feature extraction.

Could you advise me on the steps I should take to continue running the code? I would greatly appreciate your guidance in this matter.

**Comment by luigiluz** [comment]
Hi Goon,

The reason why some config_jsons have prefixes such as "1510_" and "1210_" is that I've used the date that I generated the files as an index to version the data.

Your files are generated correctly. You can use them as input files for the training and test scripts.

Please let me know if I can assist you with anything else :smiley:

**Comment by goon-13** [comment]
This is precisely what I wanted to know. It has resolved my doubts, and I am very grateful. 😁
