### ISSUE TITLE
Clarification on Usage and Purpose of Configuration Files and Scripts

### ISSUE THREAD

**Issue by goon-13** [luigiluz/automotive-ids-evaluation-framework#3]
I am reaching out for some guidance regarding the contents found in the following directory and its associated scripts:
﻿
**1. _config_jsons/multi_stage_ids
2. config_jsons/test_detection_time
3. execute_multi_stage_ids.py_**

While exploring the project, I noticed that these particular components were not mentioned in the **_README_** documentation, which has left me with some uncertainty about their purpose and how they should be utilized within the context of the project.
﻿
Could you kindly provide some insights into the function of these directories and the script? Understanding their role would be immensely helpful as I proceed with my work.
﻿
I am grateful for any assistance you can provide and look forward to your response.

**Comment by luigiluz** [comment]
Hi Goon,

Regarding items (1) and (3), these were some codes that I've previously experimented with that used a neural network to combine the outputs from the CNN and Random Forest models. However, this architecture gave poor results under the TOW-IDS dataset. For this reason, I have not continued improving it. Thanks for the mention. I have added some commits removing the codes related to this specific multi-stage architecture to avoid further confusion.

Regarding the item (2). These files are used only to evaluate the detection time of the models and load some sample data that are under the "sample_input/" folder. The data under the "sample_input/" folder only has a few lines, as we do not need to load the entire dataset to evaluate only the detection time of the models. I have also added a commit that mentions the use of these configs in the README file. Thanks for bringing this up.

Please let me know if it isn't clear yet and if you need help with anything else.

**Comment by goon-13** [comment]
Thank you, your explanation was very clear. I also appreciate the updated documentation. Should I encounter any further questions or require additional insights, I will seek your esteemed guidance once more.
